name: Hugs
main: com.gmail.nomad856.kamakarzy.Main
version: 1.3

commands:
   hug:
      description: hug target player
      usage: /hug <playername>
   kiss:
      description: kiss target player
      usage: /kiss <playername>
   marry:
      desscription: ask a player to marry you
      usage: /marry <playername>
   ido:
      desscription: accept a players request
      usage: /ido <playername>
   no:
      desscription: decline a players request
      usage: /no
   hugs:
      description: Internal plugin commands
      usage: /hugs <reload>